# Matminer 结构特征提取器学习

In [2]:
import pandas as pd
import numpy as np
from pymatgen.core import Structure

In [3]:
import os
from mp_api.client import MPRester
import pandas as pd
# Set the API key for Materials Project
API_KEY = os.getenv("MP_API_KEY")
need_fields = ['material_id', 'formula_pretty', 'composition', 'band_gap', 'is_gap_direct',
                'formation_energy_per_atom', 'energy_above_hull', 'volume', 'density', 'density_atomic',
                'symmetry', 'nsites', 'structure']

In [4]:
with MPRester(API_KEY) as mpr:
    # Get the data for the specified fields
    docs = mpr.materials.summary.search(
        fields = need_fields,
        material_ids=["mp-1204356", "mp-22862", "mp-3953"]
    )

Retrieving SummaryDoc documents:   0%|          | 0/3 [00:00<?, ?it/s]

In [5]:
SiC = docs[0]
CaCO3 = docs[1]
NaCl = docs[2]

In [6]:
# Convert the data to a pandas DataFrame
dict = {
    'material_id': [SiC.material_id, NaCl.material_id, CaCO3.material_id],
    'formula_pretty': [SiC.formula_pretty, NaCl.formula_pretty, CaCO3.formula_pretty],
    'composition': [SiC.composition, NaCl.composition, CaCO3.composition],
    'symmetry': [SiC.symmetry, NaCl.symmetry, CaCO3.symmetry],
    'nsites': [SiC.nsites, NaCl.nsites, CaCO3.nsites],
    'structure': [SiC.structure, NaCl.structure, CaCO3.structure]
}
df_raw = pd.DataFrame(dict)
df_raw

  material_id  ...                                          structure
0    mp-22862  ...   [[0. 0. 0.] Na, [2.281343 1.613153 3.951403] Cl]
1     mp-3953  ...  [[3.21199713 2.07688527 7.58523127] Ca, [0. 0....
2  mp-1204356  ...  [[ 1.42104952e-21 -5.83008571e-05 -5.73687857e...

[3 rows x 6 columns]

In [59]:
# 添加氧化态信息
# CrystalNN 算法在判断原子间键合时依赖于原子的氧化态信息来获得最佳结果。
from pymatgen.analysis.bond_valence import BVAnalyzer
bv = BVAnalyzer()
df_raw['oxi_structure'] = None
for index, row in df_raw.iterrows():
    structure = row['structure']
    bv_analyzer = BVAnalyzer()
    oxidation_states = bv_analyzer.get_oxi_state_decorated_structure(structure)
    df_raw.at[index, 'oxi_structure'] = oxidation_states

In [60]:
df_raw

  material_id  ...                                      oxi_structure
0    mp-22862  ...  [[0. 0. 0.] Na+, [2.281343 1.613153 3.951403] ...
1     mp-3953  ...  [[3.21199713 2.07688527 7.58523127] Ca2+, [0. ...
2  mp-1204356  ...  [[ 1.42104952e-21 -5.83008571e-05 -5.73687857e...

[3 rows x 7 columns]

In [61]:
structure = df_raw['oxi_structure'][0]
structure

Structure Summary
Lattice
    abc : 3.951402922131455 3.951402172480169 3.951402
 angles : 59.99998470065274 59.99999097646918 59.99999737523848
 volume : 43.625325465502776
      A : np.float64(3.422015) np.float64(0.0) np.float64(1.975702)
      B : np.float64(1.140671) np.float64(3.226306) np.float64(1.975702)
      C : np.float64(0.0) np.float64(0.0) np.float64(3.951402)
    pbc : True True True
PeriodicSite: Na (Na+) (0.0, 0.0, 0.0) [0.0, 0.0, 0.0]
PeriodicSite: Cl (Cl-) (2.281, 1.613, 3.951) [0.5, 0.5, 0.5]

## Bonding

Structure featurizers based on bonding.

### 1. BondFractions

- Matminer 库中用于计算晶体结构中各种化学键比例的特征提取器。

- BondFractions is based on the "sum over bonds" in the **Bag of Bonds approach**,
based on a method by **Hansen et. al** "Machine Learning Predictions of Molecular
Properties: Accurate Many-Body Potentials and Nonlocality in Chemical Space"(2015).

In [105]:
from matminer.featurizers.structure.bonding import BondFractions

In [106]:
df = df_raw.copy()

In [107]:
from pymatgen.analysis.local_env import VoronoiNN, JmolNN, MinimumDistanceNN
# 1. 初始化特征提取器
bf = BondFractions()
# 2. 拟合特征提取器(确定要分析的键类型)
bf.fit(df['oxi_structure'])

BondFractions()

In [108]:
# 3. 特征化结构(提取键比例)
df[bf.feature_labels()] = None
for index, row in df.iterrows():
    structure = row['oxi_structure']
    features = bf.featurize(structure)
    # 将特征添加到 DataFrame 中
    for i, label in enumerate(bf.feature_labels()):
        df.at[index, label] = features[i]
df

e:\software2\Anaconda\Lib\site-packages\pymatgen\analysis\local_env.py:3933: UserWarning: CrystalNN: cannot locate an appropriate radius, covalent or atomic radii will be used, this can lead to non-optimal results.
  nn_data = self.get_nn_data(structure, n)

,material_id,formula_pretty,composition,symmetry,nsites,structure,oxi_structure,C4+ - C4+ bond frac.,C4+ - Ca2+ bond frac.,C4+ - O2- bond frac.,C4- - C4- bond frac.,C4- - Si4+ bond frac.,Ca2+ - Ca2+ bond frac.,Ca2+ - O2- bond frac.,Cl- - Cl- bond frac.,Cl- - Na+ bond frac.,Na+ - Na+ bond frac.,O2- - O2- bond frac.,Si4+ - Si4+ bond frac.
0,mp-1204356,SiC,"(Si, C)",crystal_system=<CrystalSystem.trig: 'Trigonal'...,38,[[ 1.42104952e-21 -5.83008571e-05 -5.73687857e...,[[ 1.42104952e-21 -5.83008571e-05 -5.73687857e...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,mp-22862,NaCl,"(Na, Cl)",crystal_system=<CrystalSystem.cubic: 'Cubic'> ...,2,"[[0. 0. 0.] Na, [2.281343 1.613153 3.951403] Cl]","[[0. 0. 0.] Na+, [2.281343 1.613153 3.951403] ...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,mp-3953,CaCO3,"(Ca, C, O)",crystal_system=<CrystalSystem.trig: 'Trigonal'...,10,"[[3.21199713 2.07688527 7.58523127] Ca, [0. 0....","[[3.21199713 2.07688527 7.58523127] Ca2+, [0. ...",0.0,0.0,0.333333,0.0,0.0,0.0,0.666667,0.0,0.0,0.0,0.0,0.0

- 直接对dataframe进行操作

In [68]:
df = df_raw.copy()

In [69]:
# 直接对dataframe进行特征化
bf = BondFractions()
bf.fit_featurize_dataframe(df, "oxi_structure")

BondFractions:   0%|          | 0/3 [00:00<?, ?it/s]

,material_id,formula_pretty,composition,symmetry,nsites,structure,oxi_structure,C4+ - C4+ bond frac.,C4+ - Ca2+ bond frac.,C4+ - O2- bond frac.,C4- - C4- bond frac.,C4- - Si4+ bond frac.,Ca2+ - Ca2+ bond frac.,Ca2+ - O2- bond frac.,Cl- - Cl- bond frac.,Cl- - Na+ bond frac.,Na+ - Na+ bond frac.,O2- - O2- bond frac.,Si4+ - Si4+ bond frac.
0,mp-1204356,SiC,"(Si, C)",crystal_system=<CrystalSystem.trig: 'Trigonal'...,38,[[ 1.42104952e-21 -5.83008571e-05 -5.73687857e...,[[ 1.42104952e-21 -5.83008571e-05 -5.73687857e...,0.0,0.0,0.000000,0.0,1.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
1,mp-22862,NaCl,"(Na, Cl)",crystal_system=<CrystalSystem.cubic: 'Cubic'> ...,2,"[[0. 0. 0.] Na, [2.281343 1.613153 3.951403] Cl]","[[0. 0. 0.] Na+, [2.281343 1.613153 3.951403] ...",0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,1.0,0.0,0.0,0.0
2,mp-3953,CaCO3,"(Ca, C, O)",crystal_system=<CrystalSystem.trig: 'Trigonal'...,10,"[[3.21199713 2.07688527 7.58523127] Ca, [0. 0....","[[3.21199713 2.07688527 7.58523127] Ca2+, [0. ...",0.0,0.0,0.333333,0.0,0.0,0.0,0.666667,0.0,0.0,0.0,0.0,0.0

### 2. BagofBands

Matminer 中的一个强大特征提取器，基于 Hansen 等人在 2015 年提出的方法，用于创建固定长度的结构表示向量。它通过对库仑矩阵的处理，表示晶体结构中各种原子对之间的相互作用。

In [109]:
from matminer.featurizers.structure.bonding import BagofBonds
df = df_raw.copy()

In [72]:
bob = BagofBonds()
bob.fit([NaCl.structure])

BagofBonds()

In [75]:
features = bob.featurize(NaCl.structure)
labels = bob.feature_labels()
feat_df = pd.DataFrame([features], columns=labels)
feat_df

   Na site #0  Cl site #0  Na - Cl bond #0  Na - Cl bond #1
0  157.874667  448.794386        10.223729        10.223729

In [77]:
# 直接对dataframe进行特征化
bob = BagofBonds()
df = bob.fit_featurize_dataframe(df, "oxi_structure")
df

BagofBonds:   0%|          | 0/3 [00:00<?, ?it/s]

,material_id,formula_pretty,composition,symmetry,nsites,structure,oxi_structure,Na+ site #0,Cl- site #0,Na+ - Cl- bond #0,...,Si4+ - C4- bond #712,Si4+ - C4- bond #713,Si4+ - C4- bond #714,Si4+ - C4- bond #715,Si4+ - C4- bond #716,Si4+ - C4- bond #717,Si4+ - C4- bond #718,Si4+ - C4- bond #719,Si4+ - C4- bond #720,Si4+ - C4- bond #721
0,mp-1204356,SiC,"(Si, C)",crystal_system=<CrystalSystem.trig: 'Trigonal'...,38,[[ 1.42104952e-21 -5.83008571e-05 -5.73687857e...,[[ 1.42104952e-21 -5.83008571e-05 -5.73687857e...,0.000000,0.000000,0.000000,...,60.728955,60.728955,60.734135,60.734135,60.743214,60.743214,60.749668,60.749668,60.777604,60.777604
1,mp-22862,NaCl,"(Na, Cl)",crystal_system=<CrystalSystem.cubic: 'Cubic'> ...,2,"[[0. 0. 0.] Na, [2.281343 1.613153 3.951403] Cl]","[[0. 0. 0.] Na+, [2.281343 1.613153 3.951403] ...",157.874667,448.794386,10.223729,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,mp-3953,CaCO3,"(Ca, C, O)",crystal_system=<CrystalSystem.trig: 'Trigonal'...,10,"[[3.21199713 2.07688527 7.58523127] Ca, [0. 0....","[[3.21199713 2.07688527 7.58523127] Ca2+, [0. ...",0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

理解结果:
BagofBonds 生成的特征向量由多个"袋子"（bags）组成，每个袋子对应一种元素对（键）或单个元素。特征标签的形式为：

- 对于键: Element1 - Element2 bond #N
- 对于单个元素: Element site #N
其中 N 是该键或元素在袋子中的序号。

### 3. GlobalInstabilityIndex

Matminer 中用于评估晶体结构稳定性的特征提取器。它通过计算结构中所有原子的键价和(BVS)与其理论氧化态的偏差来评估结构的稳定性。

**注意事项:**
- 必须提供**氧化态**：结构中每个原子都必须有氧化态信息，否则计算会失败

- 仅适用于离子化合物：计算依赖于阴离子和阳离子之间的键价，所以主要适用于氧化物、氟化物等离子化合物

- 需要有表格参数：用于无序结构时，需要设置

##### 利用全局不稳定指数(GII)判断晶体结构稳定性

GII是评估晶体结构稳定性的重要指标，特别适用于离子化合物。它量化了原子实际键价和与理论氧化态之间的偏差。

**标准判断阈值**

| GII 值范围 | 稳定性评估 | 解释 |
|------------|------------|------|
| < 0.05     | 极其稳定   | 几乎无键价应力，理想结构 |
| 0.05-0.10  | 非常稳定   | 轻微键价应力，常见于实验验证的稳定结构 |
| 0.10-0.20  | 中等稳定   | 存在一定键价应力，结构可能有轻微畸变 |
| 0.20-0.30  | 轻度不稳定 | 明显键价应力，可能需要结构松弛或高温相 |
| 0.30-0.60  | 中度不稳定 | 高键价应力，结构可能只在特定条件下稳定 |
| > 0.60     | 高度不稳定 | 极高键价应力，结构可能不可合成或参数不适用 |

**材料类型与GII值解释**

不同类型的材料体系对GII值的容忍度不同：

- **简单离子晶体**（如NaCl）：通常GII < 0.10
- **氧化物钙钛矿**：通常GII < 0.20
- **复杂氧化物**：可接受的GII范围可达0.30
- **玻璃态材料和非晶材料**：GII概念应用受限

**GII指标的局限性**

1. **依赖精确的氧化态**：如氧化态分配不准确，GII值可能误导
2. **需要完整的键价参数**：一些罕见元素组合的键价参数可能不可用
3. **不考虑温度效应**：高温可能稳定高GII结构
4. **有限的化学敏感性**：无法完全捕捉共价和金属键效应

**全面评估结构稳定性**

建议将GII与其他指标结合使用：
- 结构能量计算（DFT）
- 声子谱分析
- 热力学稳定性（形成能）
- 化学键分析

In [110]:
from matminer.featurizers.structure.bonding import GlobalInstabilityIndex
df = df_raw.copy()

In [80]:
# 1. 加载包含氧化态的结构
# 注意：结构必须包含氧化态信息，否则GII计算会失败
bv = BVAnalyzer()
structure = bv.get_oxi_state_decorated_structure(NaCl.structure)
# 2. 初始化特征提取器
gii_featurizer = GlobalInstabilityIndex(r_cut=4.0)  # r_cut是搜索相邻原子的距离
# 3. 检查结构是否满足预检条件
if gii_featurizer.precheck(structure):
    # 4. 提取特征
    gii_value = gii_featurizer.featurize(structure)[0]
    print(f"全局不稳定指数 (GII): {gii_value:.4f}")
    
    # 判断结构稳定性
    if gii_value < 0.1:
        print("结构非常稳定")
    elif gii_value < 0.2:
        print("结构有一定应力")
    else:
        print("结构可能不稳定")
else:
    print("结构不满足GII计算条件")

e:\software2\Anaconda\Lib\site-packages\matminer\utils\data.py:703: ParserWarning: Length of header or names does not match length of data. This leads to a loss of data with index_col=False.
  self.params: pd.DataFrame = pd.read_csv(

全局不稳定指数 (GII): 0.0524
结构非常稳定

e:\software2\Anaconda\Lib\site-packages\spglib\spglib.py:115: DeprecationWarning: dict interface (SpglibDataset['equivalent_atoms']) is deprecated.Use attribute interface ({self.__class__.__name__}.{key}) instead
  warnings.warn(
e:\software2\Anaconda\Lib\site-packages\spglib\spglib.py:115: DeprecationWarning: dict interface (SpglibDataset['wyckoffs']) is deprecated.Use attribute interface ({self.__class__.__name__}.{key}) instead
  warnings.warn(

In [81]:
# 直接对dataframe进行特征化
gii_featurizer = GlobalInstabilityIndex(r_cut=4.0)  # r_cut是搜索相邻原子的距离
df = gii_featurizer.fit_featurize_dataframe(df, "oxi_structure")
df

e:\software2\Anaconda\Lib\site-packages\matminer\utils\data.py:703: ParserWarning: Length of header or names does not match length of data. This leads to a loss of data with index_col=False.
  self.params: pd.DataFrame = pd.read_csv(

GlobalInstabilityIndex:   0%|          | 0/3 [00:00<?, ?it/s]

,material_id,formula_pretty,composition,symmetry,nsites,structure,oxi_structure,global instability index
0,mp-1204356,SiC,"(Si, C)",crystal_system=<CrystalSystem.trig: 'Trigonal'...,38,[[ 1.42104952e-21 -5.83008571e-05 -5.73687857e...,[[ 1.42104952e-21 -5.83008571e-05 -5.73687857e...,0.092213
1,mp-22862,NaCl,"(Na, Cl)",crystal_system=<CrystalSystem.cubic: 'Cubic'> ...,2,"[[0. 0. 0.] Na, [2.281343 1.613153 3.951403] Cl]","[[0. 0. 0.] Na+, [2.281343 1.613153 3.951403] ...",0.052373
2,mp-3953,CaCO3,"(Ca, C, O)",crystal_system=<CrystalSystem.trig: 'Trigonal'...,10,"[[3.21199713 2.07688527 7.58523127] Ca, [0. 0....","[[3.21199713 2.07688527 7.58523127] Ca2+, [0. ...",0.092524

### 4. StructureHeterogeneity

Matminer 中的一个特征提取器，用于计算晶体结构中键长和原子体积的变化程度。这个类通过 Voronoi 镶嵌分析，提取描述结构不均匀性的特征，这些特征对预测材料性质（如形成能）非常有用

In [111]:
from matminer.featurizers.structure.bonding import StructuralHeterogeneity
bv = BVAnalyzer()
structure = bv.get_oxi_state_decorated_structure(NaCl.structure)

In [92]:
# 初始化特征提取器
sh = StructuralHeterogeneity(
    weight="area",  # 可选: "area"(默认), "solid_angle", "volume"
    stats=("minimum", "maximum", "mean", "range", "avg_dev")  # 自定义统计量
)
# 提取特征
features = sh.featurize(structure)

# 获取特征标签
feature_labels = sh.feature_labels()

# 创建包含特征的数据框
feat_df = pd.DataFrame([features], columns=feature_labels)
feat_df

,mean absolute deviation in relative bond length,max relative bond length,min relative bond length,minimum neighbor distance variation,maximum neighbor distance variation,mean neighbor distance variation,range neighbor distance variation,avg_dev neighbor distance variation,mean absolute deviation in relative cell size
0,1.110223e-16,1.0,1.0,2.362613e-07,2.362613e-07,2.362613e-07,1.746508e-16,8.732542e-17,0.0

**返回的特征说明:**

`StructuralHeterogeneity`返回9个特征(使用默认stats参数):

1. **mean absolute deviation in relative bond length**: 所有原子平均键长与整体平均键长偏差
2. **max relative bond length**: 最大相对键长
3. **min relative bond length**: 最小相对键长
4. **minimum neighbor distance variation**: 邻近原子距离变化的最小值
5. **maximum neighbor distance variation**: 邻近原子距离变化的最大值
6. **range neighbor distance variation**: 邻近原子距离变化的范围
7. **mean neighbor distance variation**: 邻近原子距离变化的平均值
8. **avg_dev neighbor distance variation**: 邻近原子距离变化的平均偏差
9. **mean absolute deviation in relative cell size**: 沃罗诺伊单元体积的相对变化

高结构不均匀性的值通常表明材料存在局部结构畸变或多种配位环境，这往往与不寻常的物理或电子性质相关。

这个特征提取器特别适合于研究材料的结构稳定性、形成能和热力学性能。

In [93]:
# 直接对dataframe进行特征化
df = df_raw.copy()
df = sh.fit_featurize_dataframe(df, "oxi_structure", ignore_errors=True)
df

StructuralHeterogeneity:   0%|          | 0/3 [00:00<?, ?it/s]

,material_id,formula_pretty,composition,symmetry,nsites,structure,oxi_structure,mean absolute deviation in relative bond length,max relative bond length,min relative bond length,minimum neighbor distance variation,maximum neighbor distance variation,mean neighbor distance variation,range neighbor distance variation,avg_dev neighbor distance variation,mean absolute deviation in relative cell size
0,mp-1204356,SiC,"(Si, C)",crystal_system=<CrystalSystem.trig: 'Trigonal'...,38,[[ 1.42104952e-21 -5.83008571e-05 -5.73687857e...,[[ 1.42104952e-21 -5.83008571e-05 -5.73687857e...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,mp-22862,NaCl,"(Na, Cl)",crystal_system=<CrystalSystem.cubic: 'Cubic'> ...,2,"[[0. 0. 0.] Na, [2.281343 1.613153 3.951403] Cl]","[[0. 0. 0.] Na+, [2.281343 1.613153 3.951403] ...",1.110223e-16,1.000000,1.0000,2.362613e-07,2.362613e-07,2.362613e-07,1.746508e-16,8.732542e-17,0.000000
2,mp-3953,CaCO3,"(Ca, C, O)",crystal_system=<CrystalSystem.trig: 'Trigonal'...,10,"[[3.21199713 2.07688527 7.58523127] Ca, [0. 0....","[[3.21199713 2.07688527 7.58523127] Ca2+, [0. ...",1.037200e-01,1.075444,0.7407,3.425020e-02,3.984882e-01,2.369495e-01,3.642380e-01,8.107971e-02,0.162066

### 5. MinimumRelativeDistance

是一个强大的结构特征提取器，用于计算晶体结构中每个原子位点到其最近邻的相对距离。不同于使用绝对距离，它采用相对距离计算：f_ij = r_ij / (r^atom_i + r^atom_j)，这考虑了不同元素的原子大小差异。

In [112]:
from matminer.featurizers.structure.bonding import MinimumRelativeDistances

In [96]:
# 初始化特征提取器
mrd = MinimumRelativeDistances(
    cutoff=10.0,            # 搜索近邻的最大距离
    flatten=True,           # 返回固定长度的特征向量
    include_distances=True, # 包含数值距离
    include_species=True    # 包含元素种类信息
)

mrd.fit([structure])

# 提取特征
features = mrd.featurize(structure)

# 获取特征标签
feature_labels = mrd.feature_labels()

# 创建包含特征的数据框
feat_df = pd.DataFrame([features], columns=feature_labels)
feat_df

,site #0 min. rel. dist.,site #0 specie,site #0 neighbor specie(s),site #1 min. rel. dist.,site #1 specie,site #1 neighbor specie(s)
0,0.873145,Na+,"(Na+, Na+)",0.873145,Cl-,"(Cl-, Cl-)"

In [98]:
# 只返回距离值,不包含元素种类信息
mrd_dist_only = MinimumRelativeDistances(include_distances=True, include_species=False)
mrd_dist_only.fit([structure])
# 提取特征
features = mrd_dist_only.featurize(structure)

# 获取特征标签
feature_labels = mrd_dist_only.feature_labels()

# 创建包含特征的数据框
feat_df = pd.DataFrame([features], columns=feature_labels)
feat_df

   site #0 min. rel. dist.  site #1 min. rel. dist.
0                 0.873145                 0.873145

**输出特征说明**:

当使用默认参数时(flatten=True, include_distances=True, include_species=True),每个位点生成3个特征:

1. site #{i} min. rel. dist. - 位点i到其最近邻的相对距离
2. site #{i} specie - 位点i的元素种类
3. site #{i} neighbor specie(s) - 位点i的最近邻元素种类

如果结构的位点数少于拟合时遇到的最大位点数,输出会用NaN值填充。如果位点数多于最大位点数,结果会被截断。

In [ ]:
# 直接对dataframe进行特征化
df = df_raw.copy()
mrd = MinimumRelativeDistances(
    cutoff=15,            # 搜索近邻的最大距离
    flatten=True,           # 返回固定长度的特征向量
    include_distances=True, # 包含数值距离
    include_species=False    # 包含元素种类信息
)
df = mrd.fit_featurize_dataframe(df, "oxi_structure")
df

MinimumRelativeDistances:   0%|          | 0/3 [00:00<?, ?it/s]

,material_id,formula_pretty,composition,symmetry,nsites,structure,oxi_structure,site #0 min. rel. dist.,site #1 min. rel. dist.,site #2 min. rel. dist.,...,site #28 min. rel. dist.,site #29 min. rel. dist.,site #30 min. rel. dist.,site #31 min. rel. dist.,site #32 min. rel. dist.,site #33 min. rel. dist.,site #34 min. rel. dist.,site #35 min. rel. dist.,site #36 min. rel. dist.,site #37 min. rel. dist.
0,mp-1204356,SiC,"(Si, C)",crystal_system=<CrystalSystem.trig: 'Trigonal'...,38,[[ 1.42104952e-21 -5.83008571e-05 -5.73687857e...,[[ 1.42104952e-21 -5.83008571e-05 -5.73687857e...,2.242520,2.242435,2.241448,...,2.241683,2.241696,2.241603,2.241892,2.244349,2.242435,2.244336,2.242205,2.244246,2.242456
1,mp-22862,NaCl,"(Na, Cl)",crystal_system=<CrystalSystem.cubic: 'Cubic'> ...,2,"[[0. 0. 0.] Na, [2.281343 1.613153 3.951403] Cl]","[[0. 0. 0.] Na+, [2.281343 1.613153 3.951403] ...",0.873145,0.873145,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,mp-3953,CaCO3,"(Ca, C, O)",crystal_system=<CrystalSystem.trig: 'Trigonal'...,10,"[[3.21199713 2.07688527 7.58523127] Ca, [0. 0....","[[3.21199713 2.07688527 7.58523127] Ca2+, [0. ...",0.854622,0.854622,0.817035,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Composite

Structure featurizers producing more than one kind of structure feature data.

**JarvisCFID:**

Classical Force-Field Inspired Descriptors (CFID) from Jarvis-ML.

JarvisCFID(Classical Force-Field Inspired Descriptors)是一个强大的结构特征提取器，源自NIST的Jarvis项目。它能够生成多达1,557个特征，**全面描述晶体结构的化学和结构性质**

In [113]:
from matminer.featurizers.structure.composite import JarvisCFID

In [114]:
cfid = JarvisCFID()
# 提取特征
features = cfid.featurize(structure)

# 获取特征标签
feature_labels = cfid.feature_labels()

# 创建包含特征的数据框
feat_df = pd.DataFrame([features], columns=feature_labels)
feat_df

,jml_bp_mult_atom_rad,jml_hfus_add_bp,jml_elec_aff_mult_voro_coord,jml_mol_vol_subs_atom_mass,jml_is_halogen,jml_atom_mass_subs_first_ion_en,jml_row,jml_mol_vol_mult_atom_mass,jml_voro_coord_divi_therm_cond,jml_voro_coord_subs_mp,...,jml_nn_91,jml_nn_92,jml_nn_93,jml_nn_94,jml_nn_95,jml_nn_96,jml_nn_97,jml_nn_98,jml_nn_99,jml_nn_100
0,1159.955,697.584,10.148,-8.636385,0.5,20.168032,3.0,581.612192,224.761958,-263.235,...,0.0,0.0,24.0,0.0,0.0,0.0,8.0,0.0,0.0,0.0

In [118]:
feat_df.isna().sum(axis=1)  # 检查缺失值情况

0    0
dtype: int64

In [119]:
# 直接对dataframe进行特征化
df = df_raw.copy()
df = cfid.fit_featurize_dataframe(df, "oxi_structure")
df

JarvisCFID:   0%|          | 0/3 [00:00<?, ?it/s]

,material_id,formula_pretty,composition,symmetry,nsites,structure,oxi_structure,jml_bp_mult_atom_rad,jml_hfus_add_bp,jml_elec_aff_mult_voro_coord,...,jml_nn_91,jml_nn_92,jml_nn_93,jml_nn_94,jml_nn_95,jml_nn_96,jml_nn_97,jml_nn_98,jml_nn_99,jml_nn_100
0,mp-1204356,SiC,"(Si, C)",crystal_system=<CrystalSystem.trig: 'Trigonal'...,38,[[ 1.42104952e-21 -5.83008571e-05 -5.73687857e...,[[ 1.42104952e-21 -5.83008571e-05 -5.73687857e...,3250.150000,3737.33805,5.6485,...,1.894737,0.0,26.526316,0.0,22.631579,12.0,1.263158,20.210526,4.421053,24.947368
1,mp-22862,NaCl,"(Na, Cl)",crystal_system=<CrystalSystem.cubic: 'Cubic'> ...,2,"[[0. 0. 0.] Na, [2.281343 1.613153 3.951403] Cl]","[[0. 0. 0.] Na+, [2.281343 1.613153 3.951403] ...",1159.955000,697.58400,10.1480,...,0.000000,0.0,24.000000,0.0,0.000000,0.0,8.000000,0.000000,0.000000,0.000000
2,mp-3953,CaCO3,"(Ca, C, O)",crystal_system=<CrystalSystem.trig: 'Trigonal'...,10,"[[3.21199713 2.07688527 7.58523127] Ca, [0. 0....","[[3.21199713 2.07688527 7.58523127] Ca2+, [0. ...",2075.573333,2049.48720,3.0438,...,7.200000,6.0,13.200000,4.8,4.800000,16.8,21.600000,7.200000,12.000000,13.200000

In [120]:
# 只使用部分特征类型
custom_cfid = JarvisCFID(
    use_cell=True,    # 4个特征：密度、体积等
    use_chem=False,    # 438个特征：基于化学元素性质
    use_chg=False,    # 378个特征：核心电荷分布
    use_rdf=False,     # 100个特征：径向分布函数
    use_adf=False,    # 358个特征(2x179)：角分布函数
    use_ddf=False,    # 179个特征：二面角分布函数
    use_nn=False      # 100个特征：最近邻居分布
)
df = df_raw.copy()
df = custom_cfid.fit_featurize_dataframe(df, "oxi_structure")
df

JarvisCFID:   0%|          | 0/3 [00:00<?, ?it/s]

,material_id,formula_pretty,composition,symmetry,nsites,structure,oxi_structure,jml_pack_frac,jml_vpa,jml_density,jml_log_vpa
0,mp-1204356,SiC,"(Si, C)",crystal_system=<CrystalSystem.trig: 'Trigonal'...,38,[[ 1.42104952e-21 -5.83008571e-05 -5.73687857e...,[[ 1.42104952e-21 -5.83008571e-05 -5.73687857e...,2.33352,3.227670,10.314143,0.339923
1,mp-22862,NaCl,"(Na, Cl)",crystal_system=<CrystalSystem.cubic: 'Cubic'> ...,2,"[[0. 0. 0.] Na, [2.281343 1.613153 3.951403] Cl]","[[0. 0. 0.] Na+, [2.281343 1.613153 3.951403] ...",3.08249,2.224545,21.812663,0.655991
2,mp-3953,CaCO3,"(Ca, C, O)",crystal_system=<CrystalSystem.trig: 'Trigonal'...,10,"[[3.21199713 2.07688527 7.58523127] Ca, [0. 0....","[[3.21199713 2.07688527 7.58523127] Ca2+, [0. ...",2.50919,2.703520,12.294951,0.464908

In [121]:
# 大规模处理并行化
# 对于大型数据集，可以启用并行计算
# 创建多特征提取器
# JarvisCFID计算量较大，适合单独处理
cfid_subset = JarvisCFID(use_adf=False, use_ddf=False)  # 减少计算负担的配置

# 设置并行处理
cfid_subset.set_n_jobs(-1)  # 使用所有可用CPU核心
df = df_raw.copy()
df = custom_cfid.fit_featurize_dataframe(df, "oxi_structure")
df

JarvisCFID:   0%|          | 0/3 [00:00<?, ?it/s]

,material_id,formula_pretty,composition,symmetry,nsites,structure,oxi_structure,jml_pack_frac,jml_vpa,jml_density,jml_log_vpa
0,mp-1204356,SiC,"(Si, C)",crystal_system=<CrystalSystem.trig: 'Trigonal'...,38,[[ 1.42104952e-21 -5.83008571e-05 -5.73687857e...,[[ 1.42104952e-21 -5.83008571e-05 -5.73687857e...,2.33352,3.227670,10.314143,0.339923
1,mp-22862,NaCl,"(Na, Cl)",crystal_system=<CrystalSystem.cubic: 'Cubic'> ...,2,"[[0. 0. 0.] Na, [2.281343 1.613153 3.951403] Cl]","[[0. 0. 0.] Na+, [2.281343 1.613153 3.951403] ...",3.08249,2.224545,21.812663,0.655991
2,mp-3953,CaCO3,"(Ca, C, O)",crystal_system=<CrystalSystem.trig: 'Trigonal'...,10,"[[3.21199713 2.07688527 7.58523127] Ca, [0. 0....","[[3.21199713 2.07688527 7.58523127] Ca2+, [0. ...",2.50919,2.703520,12.294951,0.464908

In [ ]:
# 特征筛选和降维
# 由于JarvisCFID生成的特征数量庞大，常配合特征选择或降维方法使用：
from sklearn.decomposition import PCA
from sklearn.feature_selection import VarianceThreshold

# 方法1：使用PCA降维
pca = PCA(n_components=50)
features_pca = pca.fit_transform(df_featurized[cfid.feature_labels()])

# 方法2：移除低方差特征
selector = VarianceThreshold(threshold=0.01)
selected_features = selector.fit_transform(df_featurized[cfid.feature_labels()])

**注意事项和常见问题**

1. 计算开销：生成所有1,557个特征对大型结构可能很耗时，考虑禁用一些特征类型或并行处理。

2. 元素兼容性：某些罕见元素可能在内部的元素描述符文件中缺失。如果遇到错误，可以使用ignore_errors=True跳过这些结构。

3. 内存考虑：处理大量结构时，可能需要批量处理以避免内存问题。

## Matrix

In [1]:
from matminer.featurizers.structure.matrix import CoulombMatrix, SineCoulombMatrix, OrbitalFieldMatrix

### 1. CoulombMatrix
用于生成结构的库仑矩阵，该矩阵表示原子核之间的库仑相互作用。

In [9]:
cm = CoulombMatrix(
    diag_elems=True, # 是否对角线元素归一化
    flatten=True, # 是否展平为一维数组
)

In [11]:
# 拟合
cm.fit([structure])
# 特征化
features = cm.featurize(structure)
# 获取特征标签
feature_labels = cm.feature_labels()
# 创建包含特征的df
feat_df = pd.DataFrame([features], columns=feature_labels)
feat_df

   coulomb matrix eig 0  ...  coulomb matrix eig 37
0            530.878122  ...              28.909057

[1 rows x 38 columns]

In [12]:
feat_df.shape

(1, 38)

In [13]:
df = df_raw.copy()
# 直接对dataframe进行特征化
cm = CoulombMatrix(diag_elems=True, flatten=True)
df = cm.fit_featurize_dataframe(df, "oxi_structure")
df

CoulombMatrix:   0%|          | 0/3 [00:00<?, ?it/s]

  material_id formula_pretty  ... coulomb matrix eig 36 coulomb matrix eig 37
0    mp-22862           NaCl  ...              0.000000              0.000000
1     mp-3953          CaCO3  ...              0.000000              0.000000
2  mp-1204356            SiC  ...             28.985266             28.909057

[3 rows x 45 columns]

### 2. SineCoulombMatrix
用于生成周期性晶体的正弦库仑矩阵变体

In [16]:
scm = SineCoulombMatrix(
    diag_elems=True, # 是否对角线元素归一化
    flatten=True # 是否展平为一维数组
)
# 拟合
scm.fit([structure])
# 特征化
features = scm.featurize(structure)
# 获取特征标签
feature_labels = scm.feature_labels()
# 创建包含特征的df
feat_df = pd.DataFrame([features], columns=feature_labels)
feat_df

   sine coulomb matrix eig 0  ...  sine coulomb matrix eig 37
0                 462.059032  ...                   23.804984

[1 rows x 38 columns]

In [17]:
# 直接对dataframe进行特征化
df = df_raw.copy()
scm = SineCoulombMatrix(diag_elems=True, flatten=True)
df = scm.fit_featurize_dataframe(df, "oxi_structure")
df

SineCoulombMatrix:   0%|          | 0/3 [00:00<?, ?it/s]

  material_id  ... sine coulomb matrix eig 37
0    mp-22862  ...                   0.000000
1     mp-3953  ...                   0.000000
2  mp-1204356  ...                  23.804984

[3 rows x 45 columns]

### 3. OrbitalFieldMatrix
用于基于相邻原子的价层电子生成表示。

In [20]:
ofm = OrbitalFieldMatrix(
    period_tag=False, # 是否包含周期标签
    flatten=True, # 是否展平为一维数组
)
# 特征化
features = ofm.featurize(structure) 
# 获取特征标签
feature_labels = ofm.feature_labels()
# 创建包含特征的df
feat_df = pd.DataFrame([features], columns=feature_labels)
feat_df

   OFM: s^1 - s^1  OFM: s^1 - s^2  ...  OFM: f^14 - f^13  OFM: f^14 - f^14
0             0.0             0.0  ...               0.0               0.0

[1 rows x 1024 columns]

In [21]:
# 直接对dataframe进行特征化
df = df_raw.copy()
ofm = OrbitalFieldMatrix(period_tag=False, flatten=True)
df = ofm.fit_featurize_dataframe(df, "oxi_structure")
df

OrbitalFieldMatrix:   0%|          | 0/3 [00:00<?, ?it/s]

  material_id formula_pretty  ... OFM: f^14 - f^13 OFM: f^14 - f^14
0    mp-22862           NaCl  ...              0.0              0.0
1     mp-3953          CaCO3  ...              0.0              0.0
2  mp-1204356            SiC  ...              0.0              0.0

[3 rows x 1031 columns]

## Misc

In [22]:
from matminer.featurizers.structure.misc import EwaldEnergy, StructureComposition, XRDPowderPattern

### 1. EwaldEnergy
用于计算结构的库仑相互作用能。
Ewald 能量指的是：

在周期性体系（如晶体）中计算离子间库伦相互作用时，用 Ewald Summation（埃瓦尔德求和法） 得到的总电势能。

In [28]:
ee = EwaldEnergy(
    accuracy=4, # 精度
    per_atom=True, # 是否返回每个原子的能量
)
# 特征化
features = ee.featurize(structure)
# 获取特征标签
feature_labels = ee.feature_labels()
# 创建包含特征的df
feat_df = pd.DataFrame([features], columns=feature_labels)
feat_df

   ewald_energy_per_atom
0              -4.503149

In [29]:
# 直接对dataframe进行特征化
df = df_raw.copy()
ee = EwaldEnergy(accuracy=4, per_atom=True)
df = ee.fit_featurize_dataframe(df, "oxi_structure")
df

EwaldEnergy:   0%|          | 0/3 [00:00<?, ?it/s]

  material_id  ... ewald_energy_per_atom
0    mp-22862  ...             -4.503149
1     mp-3953  ...            -45.229812
2  mp-1204356  ...           -100.163869

[3 rows x 8 columns]

### 2. StructureComposition
用于提取与结构组成相关的特征。它本质上是一个包装器，它在结构的成分上调用基于成分的特征器。

In [30]:
from matminer.featurizers.composition import ElementProperty
ep = ElementProperty.from_preset(preset_name="magpie")
sc = StructureComposition(featurizer=ep)
# 特征化
features = sc.featurize(structure)
# 获取特征标签
feature_labels = sc.feature_labels()
# 创建包含特征的df
feat_df = pd.DataFrame([features], columns=feature_labels)
feat_df

e:\software2\Anaconda\Lib\site-packages\matminer\utils\data.py:326: UserWarning: MagpieData(impute_nan=False):
In a future release, impute_nan will be set to True by default.
                    This means that features that are missing or are NaNs for elements
                    from the data source will be replaced by the average of that value
                    over the available elements.
                    This avoids NaNs after featurization that are often replaced by
                    dataset-dependent averages.
  warnings.warn(f"{self.__class__.__name__}(impute_nan=False):\n" + IMPUTE_NAN_WARNING)

   MagpieData minimum Number  ...  MagpieData mode SpaceGroupNumber
0                       11.0  ...                              64.0

[1 rows x 132 columns]

In [33]:
# 直接对dataframe进行特征化
df = df_raw.copy()
ep = ElementProperty.from_preset(preset_name="magpie")
sc = StructureComposition(featurizer=ep)
df = sc.featurize_dataframe(df, "oxi_structure")
df

e:\software2\Anaconda\Lib\site-packages\matminer\utils\data.py:326: UserWarning: MagpieData(impute_nan=False):
In a future release, impute_nan will be set to True by default.
                    This means that features that are missing or are NaNs for elements
                    from the data source will be replaced by the average of that value
                    over the available elements.
                    This avoids NaNs after featurization that are often replaced by
                    dataset-dependent averages.
  warnings.warn(f"{self.__class__.__name__}(impute_nan=False):\n" + IMPUTE_NAN_WARNING)

StructureComposition:   0%|          | 0/3 [00:00<?, ?it/s]

  material_id  ... MagpieData mode SpaceGroupNumber
0    mp-22862  ...                             64.0
1     mp-3953  ...                             12.0
2  mp-1204356  ...                            194.0

[3 rows x 139 columns]

### 3. XRDPowderPattern
用于生成结构的粉末衍射图。

In [34]:
xrd = XRDPowderPattern(
    two_theta_range=(0, 90), # 2θ范围
    bw_method=0.05
)
# 特征化
features = xrd.featurize(structure)
# 获取特征标签
feature_labels = xrd.feature_labels()
# 创建包含特征的df
feat_df = pd.DataFrame([features], columns=feature_labels)
feat_df

           xrd_0          xrd_1  ...    xrd_89        xrd_90
0  1.498543e-212  1.233416e-197  ...  0.000002  5.502921e-09

[1 rows x 91 columns]

In [36]:
# 直接对dataframe进行特征化
df = df_raw.copy()
xrd = XRDPowderPattern(two_theta_range=(0, 90), bw_method=0.05)
df = xrd.featurize_dataframe(df, "oxi_structure")
df

XRDPowderPattern:   0%|          | 0/3 [00:00<?, ?it/s]

  material_id formula_pretty  ...        xrd_89        xrd_90
0    mp-22862           NaCl  ...  1.552000e-06  5.502921e-09
1     mp-3953          CaCO3  ...  1.496136e-10  2.248082e-14
2  mp-1204356            SiC  ...  1.429261e-07  2.225551e-10

[3 rows x 98 columns]

## Order
Structure featurizers based on packing or ordering.

In [37]:
from matminer.featurizers.structure.order import DensityFeatures, ChemicalOrdering, MaximumPackingEfficiency, StructuralComplexity

### 1. DensityFeatures
用于计算密度和类密度特征

In [39]:
densityFeat = DensityFeatures(desired_features=['density', 'vpa'])
# 特征化
features = densityFeat.featurize(structure)
# 获取特征标签
feature_labels = densityFeat.feature_labels()
# 创建包含特征的df
feat_df = pd.DataFrame([features], columns=feature_labels)
feat_df

    density        vpa
0  2.224545  21.812663

In [40]:
# 直接对dataframe进行特征化
df = df_raw.copy()
densityFeat = DensityFeatures(desired_features=['density', 'vpa'])
df = densityFeat.featurize_dataframe(df, "oxi_structure")
df

DensityFeatures:   0%|          | 0/3 [00:00<?, ?it/s]

  material_id formula_pretty  ...   density        vpa
0    mp-22862           NaCl  ...  2.224545  21.812663
1     mp-3953          CaCO3  ...  2.703520  12.294951
2  mp-1204356            SiC  ...  3.227670  10.314143

[3 rows x 9 columns]

### 2. ChemicalOrdering
用于量化结构中物种排序与随机排序的偏差程度。

In [41]:
co = ChemicalOrdering()

# 特征化
features = co.featurize(structure)
# 获取特征标签
feature_labels = co.feature_labels()
# 创建包含特征的df
feat_df = pd.DataFrame([features], columns=feature_labels)
feat_df

   mean ordering parameter shell 1  ...  mean ordering parameter shell 3
0                         0.999999  ...                         0.999998

[1 rows x 3 columns]

In [43]:
# 直接对dataframe进行特征化
df = df_raw.copy()
co = ChemicalOrdering()
df = co.featurize_dataframe(df, "oxi_structure", ignore_errors=True)
df

ChemicalOrdering:   0%|          | 0/3 [00:00<?, ?it/s]

  material_id  ... mean ordering parameter shell 3
0    mp-22862  ...                        0.999998
1     mp-3953  ...                        0.120077
2  mp-1204356  ...                             NaN

[3 rows x 10 columns]

### 3. MaximumPackingEfficiency
用于计算结构的最大可能堆积效率。

In [44]:
mpe = MaximumPackingEfficiency()
# 特征化
features = mpe.featurize(structure)
# 获取特征标签
feature_labels = mpe.feature_labels()
# 创建包含特征的df
feat_df = pd.DataFrame([features], columns=feature_labels)
feat_df

   max packing efficiency
0                0.523599

In [46]:
# 直接对dataframe进行特征化
df = df_raw.copy()
mpe = MaximumPackingEfficiency()
df = mpe.featurize_dataframe(df, "oxi_structure", ignore_errors=True)
df

MaximumPackingEfficiency:   0%|          | 0/3 [00:00<?, ?it/s]

  material_id  ... max packing efficiency
0    mp-22862  ...               0.523599
1     mp-3953  ...               0.185069
2  mp-1204356  ...               0.339431

[3 rows x 8 columns]

### 3. StructuralComplexity
用于计算结构的香农信息熵，以此来衡量结构的复杂性

In [48]:
sc = StructuralComplexity()
# 特征化
features = sc.featurize(structure)
# 获取特征标签
feature_labels = sc.feature_labels()
# 创建包含特征的df
feat_df = pd.DataFrame([features], columns=feature_labels)
feat_df

   structural complexity per atom  structural complexity per cell
0                             1.0                             2.0

In [49]:
# 直接对dataframe进行特征化
df = df_raw.copy()
sc = StructuralComplexity()
df = sc.featurize_dataframe(df, "oxi_structure", ignore_errors=True)
df

StructuralComplexity:   0%|          | 0/3 [00:00<?, ?it/s]

  material_id  ... structural complexity per cell
0    mp-22862  ...                       2.000000
1     mp-3953  ...                      13.709506
2  mp-1204356  ...                     199.421246

[3 rows x 9 columns]

## RDF

In [51]:
from matminer.featurizers.structure.rdf import RadialDistributionFunction, PartialRadialDistributionFunction, ElectronicRadialDistributionFunction

### 1. RadialDistributionFunction
用于计算晶体结构的径向分布函数 (RDF)。

In [52]:
rdf = RadialDistributionFunction(
    cutoff=10,  # 计算rdf的最大距离（以Å为单位）
    bin_size=0.1,  # 每个bin的大小（以Å为单位）
)
# 特征化
features = rdf.featurize(structure)
# 获取特征标签
feature_labels = rdf.feature_labels()
# 创建包含特征的df
feat_df = pd.DataFrame([features], columns=feature_labels)
feat_df

   rdf [0.00000 - 0.10000]A  ...  rdf [9.90000 - 10.00000]A
0                       0.0  ...                        0.0

[1 rows x 100 columns]

In [53]:
# 直接对dataframe进行特征化
df = df_raw.copy()
rdf = RadialDistributionFunction(cutoff=10, bin_size=0.1)
df = rdf.featurize_dataframe(df, "oxi_structure")
df

RadialDistributionFunction:   0%|          | 0/3 [00:00<?, ?it/s]

  material_id  ... rdf [9.90000 - 10.00000]A
0    mp-22862  ...                  0.000000
1     mp-3953  ...                 13.044909
2  mp-1204356  ...                 78.592631

[3 rows x 107 columns]

### 2. PartialRadialDistributionFunction
类用于计算晶体结构的局部径向分布函数 (PRDF)。

In [54]:
prdf = PartialRadialDistributionFunction(
    cutoff=10,  # 计算rdf的最大距离（以Å为单位）
    bin_size=0.1,  # 每个bin的大小（以Å为单位）
)
# 拟合
prdf.fit([structure])
# 特征化
features = prdf.featurize(structure)
# 获取特征标签
feature_labels = prdf.feature_labels()
# 创建包含特征的df
feat_df = pd.DataFrame([features], columns=feature_labels)  
feat_df

   Na-Na PRDF r=0.00-0.10  ...  Cl-Cl PRDF r=9.90-10.00
0                     0.0  ...                      0.0

[1 rows x 300 columns]

In [55]:
# 直接对dataframe进行特征化
df = df_raw.copy()
prdf = PartialRadialDistributionFunction(cutoff=10, bin_size=0.1)
df = prdf.fit_featurize_dataframe(df, "oxi_structure")
df

PartialRadialDistributionFunction:   0%|          | 0/3 [00:00<?, ?it/s]

  material_id formula_pretty  ... O-O PRDF r=9.80-9.90 O-O PRDF r=9.90-10.00
0    mp-22862           NaCl  ...             0.000000              0.000000
1     mp-3953          CaCO3  ...             0.032808              0.080379
2  mp-1204356            SiC  ...             0.000000              0.000000

[3 rows x 4407 columns]

### 3. ElectronicRadialDistributionFunction
用于计算固有的电子径向分布函数 (ReDF)。

In [62]:
redf = ElectronicRadialDistributionFunction(
    cutoff=10,  # 计算rdf的最大距离（以Å为单位）
    dr=0.05,  # ReDF的bin宽度（以Å为单位）
)
# 特征化
features = redf.featurize(structure)
# 获取特征标签
feature_labels = redf.feature_labels()
# 创建包含特征的df
feat_df = pd.DataFrame([features], columns=feature_labels)
feat_df

   ReDF [0.00000 - 0.05000]A  ...  ReDF [10.00000 - 10.00000]A
0                        0.0  ...                          0.0

[1 rows x 201 columns]

In [64]:
# 直接对dataframe进行特征化
df = df_raw.copy()
redf = ElectronicRadialDistributionFunction(cutoff=10, dr=0.05)
redf.featurize_dataframe(df, "oxi_structure")
df

ElectronicRadialDistributionFunction:   0%|          | 0/3 [00:00<?, ?it/s]

  material_id  ...                                      oxi_structure
0    mp-22862  ...  [[0. 0. 0.] Na+, [2.281343 1.613153 3.951403] ...
1     mp-3953  ...  [[3.21199713 2.07688527 7.58523127] Ca2+, [0. ...
2  mp-1204356  ...  [[ 1.42104952e-21 -5.83008571e-05 -5.73687857e...

[3 rows x 7 columns]

## Sites
Structure featurizers based on aggregating site features.

In [67]:
from matminer.featurizers.structure.sites import SiteStatsFingerprint

### 1. SiteStatsFingerprint
类用于计算结构中所有位点属性的统计信息。
它首先使用位点特征器类（请参阅 site.py 了解选项）来计算结构中每个位点的特征，然后通过测量每个属性的统计信息来计算整个结构的特征。
可以选择仅计算具有一定氧化态范围的位点的统计信息（例如，仅阴离子）。

In [70]:
from matminer.featurizers.site import CoordinationNumber
from pymatgen.analysis.local_env import VoronoiNN, JmolNN, MinimumDistanceNN
ssf = SiteStatsFingerprint(
    site_featurizer=CoordinationNumber(nn=VoronoiNN()), # 使用Voronoi邻居
    stats=["mean", "std_dev"], # 统计量：均值和标准差
)

In [71]:
# 拟合
ssf.fit([structure])
# 特征化
features = ssf.featurize(structure)
# 获取特征标签
feature_labels = ssf.feature_labels()
# 创建包含特征的df
feat_df = pd.DataFrame([features], columns=feature_labels)
feat_df

   mean CN_VoronoiNN  std_dev CN_VoronoiNN
0               14.0                   0.0

In [75]:
# 直接对dataframe进行特征化
df = df_raw.copy()
ssf.featurize_dataframe(df, "oxi_structure")
df

SiteStatsFingerprint:   0%|          | 0/3 [00:00<?, ?it/s]

  material_id  ...                                      oxi_structure
0    mp-22862  ...  [[0. 0. 0.] Na+, [2.281343 1.613153 3.951403] ...
1     mp-3953  ...  [[3.21199713 2.07688527 7.58523127] Ca2+, [0. ...
2  mp-1204356  ...  [[ 1.42104952e-21 -5.83008571e-05 -5.73687857e...

[3 rows x 7 columns]

## Symmetry

In [76]:
from matminer.featurizers.structure.symmetry import GlobalSymmetryFeatures, Dimensionality

### 1. GlobalSymmetryFeatures
用于确定结构的对称性特征，例如空间群号和晶体系统。

In [77]:
gsf = GlobalSymmetryFeatures(desired_features=["spacegroup_num", "crystal_system", "crystal_system_int"])
# 特征化
features = gsf.featurize(structure)
# 获取特征标签
feature_labels = gsf.feature_labels()
# 创建包含特征的df
feat_df = pd.DataFrame([features], columns=feature_labels)
feat_df

   spacegroup_num crystal_system  crystal_system_int
0             225          cubic                   1

In [78]:
# 直接对dataframe进行特征化
df = df_raw.copy()
gsf = GlobalSymmetryFeatures(desired_features=["spacegroup_num", "crystal_system", "crystal_system_int"])
df = gsf.featurize_dataframe(df, "oxi_structure")
df

GlobalSymmetryFeatures:   0%|          | 0/3 [00:00<?, ?it/s]

  material_id formula_pretty  ... crystal_system crystal_system_int
0    mp-22862           NaCl  ...          cubic                  1
1     mp-3953          CaCO3  ...       trigonal                  3
2  mp-1204356            SiC  ...       trigonal                  3

[3 rows x 10 columns]

### 2. Dimensionality
用于确定结构的维度。
维度定义如下：
- 1：线性原子链或孤立原子/无键
- 2：分层
- 3：3D 连接结构

In [79]:
d = Dimensionality()
# 特征化
features = d.featurize(structure)
# 获取特征标签
feature_labels = d.feature_labels()
# 创建包含特征的df
feat_df = pd.DataFrame([features], columns=feature_labels)
feat_df

   dimensionality
0               3

In [80]:
# 直接对dataframe进行特征化
df = df_raw.copy()
d = Dimensionality()
df = d.featurize_dataframe(df, "oxi_structure")
df

Dimensionality:   0%|          | 0/3 [00:00<?, ?it/s]

  material_id  ... dimensionality
0    mp-22862  ...              3
1     mp-3953  ...              3
2  mp-1204356  ...              3

[3 rows x 8 columns]